### ISSUE TITLE
反应速度

### ISSUE THREAD

**Issue by ucxl** [linhao1998/ChatGPTClient#1]
我感觉api调用反应速度没有官网上的快，不知道为什么，同样的梯子

**Comment by linhao1998** [comment]
我使用是快于官网的，而且没有经常需要刷新的情况，请求就给回复，你是使用本项目构建的APP吗

**Comment by ucxl** [comment]
是的，我生成app试了一下，chatgpt回复出来的字比较慢，没有找到原因，但我在官网上同样的问话 回复就很快

**Comment by linhao1998** [comment]
api调用我试过可以不受限梯子节点区域限制的，你可以使用香港或者亚洲区域内更快的节点试下，APP我也发送给我朋友试过，发现比官网是快的。另外，项目我一直也在完善中，代码也一直在变动，建议使用最新的版本。

**Comment by linhao1998** [comment]
> 是的，我生成app试了一下，chatgpt回复出来的字比较慢，没有找到原因，但我在官网上同样的问话 回复就很快

api调用我试过可以不受限梯子节点区域限制的，你可以使用香港或者亚洲区域内更快的节点试下，APP我也发送给我朋友试过，发现比官网是快的。另外，项目我一直也在完善中，代码也一直在变动，建议使用最新的版本。

**Comment by ucxl** [comment]
嗯，感谢大神
